minard/pcadb.py
Small correction: fiber 27 is indeed installed.
=> Update fiber 27 status to installed

minard/templates/nearline.html
Added code to handle return codes 2, 3, and 4.
=> Add more return statuses to nearline template

minard/HLDQTools.py, minard/templates/calibdq.html, minard/templates/calibdq_tellie.html, minard/templates/calibdq_tellie_run.html, minard/templates/calibdq_tellie_subrun.html, minard/templates/layout.html, minard/tools.py, minard/views.py
This PR adds the webpage for the TELLIEDQ information. The code requires access to couchDB, the password is set using the COUCHDB_PASSWORD enviroment variable.
=> Telliedq changes

minard/templates/calibdq_tellie_subrun.html
Bugfix to obtain  images for TELLIE DQ page.
=> Changed URL for some TELLIE DQ images

minard/noisedb.py, minard/templates/layout.html, minard/templates/noise.html, minard/templates/noise_run_detail.html, minard/views.py
Might need to debug path names for the noise plots.
=> Adds pmt noise monitoring page

minard/HLDQTools.py, minard/templates/calibdq_tellie.html, minard/views.py
This PR adds in multiple pages for the TELLIE DQ results. The changes also include formatting issues to show TELLIE runs where the DQ code appears not to have been run.
=> Multiple pages for TELLIE DQ runs

minard/noisedb.py, minard/templates/noise.html
Reverse sort order (recent run first).
Add a column of run average QHL HHP.
=> Update to pmt noise home table

minard/noisedb.py, minard/templates/noise.html, minard/templates/noise_run_detail.html
Add buttons to download noise table, monitoring table, or rat log files. Also adds PGT nhit monitor to noise home.
=> Add download buttons to noise monitor.

minard/HLDQTools.py, minard/templates/physicsdq_run_number.html
- Only show physics runs
- Remove old checks which are not used.
=> Updates to the physics DQ pages

minard/detector_state.py
Also add information about tubii attenuating mode.
=> Get mtc/tubii keys from run state

minard/pcadb.py, minard/templates/pca_run_detail.html, minard/templates/pcatellie.html, minard/views.py
This updates the fiber-map, orders the run list in descending order and shows the flags in thr run-detail page.
=> pcatellie: small updates

minard/polling.py, minard/static/js/scatter_plot_rates.js, minard/templates/check_rates.html, minard/templates/check_rates_history.html, minard/templates/cmos_rates_check.html, minard/templates/layout.html, minard/views.py
- New cmos rates check page to check the cmos rates and warn about channels that might be misbehaving
- Add log scale option for cmos rate plot
- Add hovertext for cmos rate plot
=> add page to warn about cmos rates

minard/static/js/scatter_plot_rates.js
=> Change the number of xaxis ticks

minard/detector_state.py, minard/templates/ecal_state_diff.html, minard/views.py
sorry, screwed up my last pull request, these changes were supposed to be part of that one.
=> update ecal diff template 

minard/db.py, minard/pingcratesdb.py, minard/templates/pingcrates.html
I separated out the ping crates updates from #108 so that we can continue to use the ping crates page once https://github.com/snoplus/nearline/pull/139 is merged on the nearline, without needing to merge all the changes in #108.
=> Update to ping crates page

minard/nearline_monitor.py, minard/templates/nearline_monitoring_summary.html, minard/triggerclockjumpsdb.py, minard/views.py
Currently selecting a run does not work on the nearline monitoring page.
=> Allow user to select run on nearline monitoring page

minard/channelflagsdb.py, minard/nearline_monitor.py, minard/occupancy.py, minard/templates/channelflags.html, minard/templates/occupancy_by_trigger.html, minard/templates/pingcrates.html, minard/templates/trigger_clock_jump.html, minard/views.py
and make the trigger occupancy page more clear regarding which slots failed
=> add 'no data found' message for nearline jobs

minard/templates/nearline_monitoring_summary.html
for the nearline monitoring page
=> add link to nearline log files

minard/channelflagsdb.py, minard/nearline_monitor.py, minard/occupancy.py, minard/pingcratesdb.py, minard/polling.py, minard/templates/channelflags.html, minard/templates/nearline_monitoring_summary.html, minard/templates/occupancy_by_trigger.html, minard/templates/pingcrates.html, minard/templates/trigger_clock_jump.html, minard/triggerclockjumpsdb.py, minard/views.py
Also adds PMT type counts to channel flags page. Plus a couple bug fixes and small changes.
=> Add run range option to nearline monitoring page

minard/channelflagsdb.py, minard/nearline_monitor.py, minard/nearline_settings.py, minard/occupancy.py, minard/pingcratesdb.py, minard/run_list.py, minard/templates/channelflags.html, minard/templates/nearline_monitoring_summary.html, minard/templates/nearline_summary.html, minard/templates/occupancy_by_trigger.html, minard/templates/pingcrates.html, minard/templates/trigger_clock_jump.html, minard/triggerclockjumpsdb.py, minard/views.py
Also a couple unrelated bug fixes.
=> Add a "gold runs" button to nearline monitoring pages

minard/muonsdb.py, minard/nearline_monitor.py, minard/templates/muon_list.html, minard/views.py
The query to get the missed muon information was very slow over large run ranges. This should fix that.
=> rewrite muon table queries

minard/detector_state.py
Recently we had many of these channels on 15/9 unfortunately
=> warn about channels not being read out but are at HV

minard/dropout.py, minard/templates/dropout.html, minard/templates/dropout_detail.html, minard/templates/layout.html, minard/views.py
This creates a page to view the results of the the "Dropout Evaluator" nearline job. I'd like to, in the future generalize the visual I use for the "/dropout" page so it can be used elsewhere. But I probably won't have time to do that in the immediate future so this is good enough as it is now I think.
=> Dropout monitoring page

minard/detector_state.py, minard/nearline_monitor.py, minard/nearlinedb.py, minard/templates/nearline_monitoring_summary.html, minard/views.py
- Allow sorting by run type for nearline monitoring page
- Fix some bugs associated with sorting for nearline failure page
=> Update to nearline pages

minard/detector_state.py
=> Update check to work better when only timing rack is on

minard/channeldb.py, minard/templates/channel_database.html, minard/templates/channel_status.html, minard/views.py
- Add GTValid information (database is currently empty)
- Add Vthr information to channel status page even when the detector is off, using the most recent run
- Update to channel database page to list the status similarly to the channel status page and to include a filter for pmt type.
=> Updates to channel database and channel status pages

minard/detector_state.py
Channel 6 seemed to fry today so we swapped to channel 5
=> update tubii channel mapping

minard/templates/check_rates.html
Fix bug with check rates crate view for base currents updating when run number is changed.
=> check rates base current crate view fix 

minard/muonsdb.py, minard/nearline_monitor.py, minard/run_list.py, minard/templates/channelflags.html, minard/templates/muon_list.html, minard/templates/nearline_monitoring_summary.html, minard/templates/occupancy_by_trigger.html, minard/templates/pingcrates.html, minard/templates/trigger_clock_jump.html, minard/views.py
- Change the way the gold button looks
- Add an "atmospheric" button to the muon page
- Largely rewrite all of the code responsible for querying the muon tables
=> New features for nearline monitoring page

minard/gain_monitor.py, minard/templates/crate_gain_monitor.html, minard/views.py
=> fix crate gain page when a run is missing data for a crate

minard/channeldb.py, minard/static/js/scatter_plot_disc.js, minard/templates/discriminator_info.html, minard/views.py
This adds plots that show the average discriminator threshold by crate / slot to the discriminator info page.
=> Discriminator threshold average by crate / slot

minard/muonsdb.py
The info should come from the most recent reprocessing.
=> Make sure all the muon info is ordered by timestamp

minard/detector_state.py
Not a great solution, but I can't seem to get the order by to work using the current format.
=> Fix nhit monitor sorting

bin/minard-dispatch, minard/static/js/snostream.js, minard/views.py
This hopefully fixes marking polling in the stream.
=> mark polling as a rate, as it was before with the EXT2

minard/dropout.py, minard/templates/dropout.html, minard/templates/dropout_detail.html
Adds info about the chi2 of dropout fits. This PR  relies on a similar change to the nearline, but it doesn't require it.
=> add chi2 info about dropout fits

minard/activity.py, minard/templates/deck_activity.html
As per Erica's suggestion, make clearing the deck separate from going on/off deck so that you can just use the GUI once to clear the deck.
=> update for new 'clearing' direction

README, minard/shifter_information.py, minard/templates/_formhelpers.html, minard/templates/layout.html, minard/templates/shifter_information.html, minard/views.py
To be used by the alarmshifter script for email and text alerts.
=> Add new page to keep track of shifter information

minard/detector_state.py, minard/templates/nhit_monitor_thresholds_nearline.html, minard/views.py
To look back at the results of old nhit monitors.
=> Allow sorting nhit monitors by run range

minard/shifter_information.py, minard/templates/shifter_information.html
Also allow for different length phone numbers (Armin's request).
=> let shifter know the text alerts are not implemented 

minard/HLDQTools.py, minard/views.py
Fixes address issues present at last TELLIE PCA attempt.
=> Fixes to TELLIE DQ and SMELLIE DQ display

minard/scintillator_level.py, minard/templates/layout.html, minard/templates/scint_level.html, minard/views.py
Probably only useful during scintillator filling. The same information is pushed to RATDB so its probably useful to monitor it a bit.
=> add plot for scintillator level

minard/burst.py, minard/static/js/burst.js, minard/static/js/l2.js, minard/templates/burst.html, minard/templates/burst_run_detail.html, minard/templates/l2.html, minard/views.py
- updated plots, 
- new plots, 
- fix for times, 
- added UTC date and time,
- added GTIDs and range,
- added Stonehenge settings load from redis and view,
- added dynamic threshold view,
- reversed couch load,
- cleaned up the couch view
=> Updates to L2 - Burst Trigger system

minard/activity.py, minard/templates/deck_activity.html
deck activity table is being replaced by the logbook table, which will be updated on a tablet sitting by the deck door.
=> update to use logbook table

minard/templates/deck_activity.html
=> fix bug in deck activity html

minard/scintillator_level.py, minard/templates/layout.html, minard/templates/scint_level.html, minard/views.py
New nearline table keeps track of the AV offset. Here I've added a plot of the AV z-offset to the scintillator level page.
=> add av offset calculation and plot to scint. level page

minard/burst.py, minard/static/js/burst_form.js, minard/static/js/l3.js, minard/templates/burst.html, minard/templates/burst_l3.html, minard/templates/burst_run_detail.html, minard/templates/burst_run_detail_l3.html, minard/templates/l2.html, minard/templates/l3.html, minard/templates/layout.html, minard/views.py
Supernova Burst Trigger: updates to Level 2 and addition of Level 3 monitoring.
Global
-> changed layout: renamed L2 to Supernova, added Level 3 pages.
L2
-> improvements to visuals to L2 list table
-> changed layout of run detail page: grouping similar elements in tables, made headers bold
L3
-> made overview page, including list of cuts (loaded from couch), loading variables from redis
-> made burst list table, slightly different variables loaded from couch than L2
-> run detail page: follows the new scheme of L2, some additional plots and details
Other:
-> corresponding functions in .js, burst.py, views.py ...
=> Sn burst trigger L3

minard/templates/burst_l3.html, minard/templates/burst_run_detail_l3.html
- fix for review form submit redirect
- fix for Next/Back button redirects on L3 list page
- adding high NHit threshold to L3 table
=> SN L3 fixes

minard/detector_state.py, minard/templates/detector_state_check.html, minard/views.py
1) Organize the detector state check messages
2) Fix a small bug on the MTCA+ page
=> Detector state check changes

minard/burst.py, minard/static/js/l2.js, minard/templates/burst_l3.html, minard/templates/burst_run_detail.html, minard/templates/burst_run_detail_l3.html, minard/templates/l2.html, minard/views.py
-> Adding option to sort bursts by significance
-> Minor additions and modifications regarding new IBD buffer
=> Supernova Burst Trigger: update

minard/light_level.py, minard/templates/layout.html, minard/templates/light_level.html, minard/templates/light_level_plots.html, minard/templates/light_level_summary.html, minard/views.py
=> Add new page for monitoring the 210Po nhits peak for physics runs 

minard/RSTools.py, minard/db.py, minard/templates/layout.html, minard/templates/runselection.html, minard/templates/runselection_run.html, minard/views.py, requirements.txt
Adds the run-selection page to minard:
- Displays the RS results for runs "live" (as they go through run-selection continuously on nlug).
- Shows which run list each run is in, and allows the user to change which run lists it is in.
- Changes to run lists are also displayed in a history table.
- Tested running it on my laptop successfully.
=> Run selection views

minard/RSTools.py
=> Change use of format function to be python2.6 compatible

requirements.txt
=> Add Pillow to requirements.txt

minard/pca_processing.py
With the change of how we symlink directories with plots, some paths to files now have different structure.
=> PCATELLIE: fix for file paths

minard/pca_processing.py
new way to load the path for the 'static' folder...
=> updated way to get file path

minard/RSTools.py, minard/templates/layout.html, minard/templates/runselection_plots.html, minard/views.py
This PR is to create a page on minard which plots the run selection plots (like the ones presented in the weekly update on the DWG calls) for a user given date range. This has been approved by the run selection group. There are also two small bug fixes to the run selection page code.
Speak to me (Katharine) or Matt if there are any questions.
Still to do before merging:
- decide on a default date range
- The page has been tested by me and Matt for bugs but further testing may be required
@mmdepatie @ecaden
=> Run selection plotting page

minard/RSTools.py
deck_activity and run_list_opinion show logs instead of number of logs on minard page for specific run
=> Deck activity log display

minard/activity.py, minard/templates/deck_activity.html
Added columns for deck lights and DCR lights info on the deck and DCR activity page.
=> Add deck and DCR lights info to deck activity page

minard/templates/radon_monitor.html
Going to run out of dates that can be selected at the end of the year, so adding more. Also a tweak to the y-axis as none of the important rates are this low
=> Increased the number of years that can be selected. Changed the axis
