snoplus/minard

minard/detector_state.py
minard/static/css/detector_state.css
minard/static/js/crate.js
minard/static/js/detector_state.js
minard/templates/state.html
minard/views.py

This adds displays for MTCA thresholds as well as channel thresholds and a few other channel level items
Also added are a few interesting values for the CAEN and many of the less interesting ones are hidden away.
There's also now a summary of some of the most critical values displayed at the top of the page,
this gives the masked in triggers, the thresholds for those triggers (the ones that have thresholds anyways), the number of N100/N20 Triggers enabled, the number of sequencers enabled and the number of crates that are on.
There's a number of aesthetic changes here too including having a more "telescoping" look to the collapsible display. Also the colors for many of the things can be configured by the user by adding the appropriate request to the url (e.g. …

Lots of additions and improvements to detector state page

---

minard/templates/nearline.html

Nearline has been updated with a new exit code to be used when a nonexecutable file is passed; this update will display a more useful message on the monitoring page in this case.

Update nearline template with additional status code

---

minard/nlrat.py
minard/static/css/ratrun.css
minard/static/js/rat.js
minard/templates/layout.html
minard/templates/rathome.html
minard/templates/ratrun.html
minard/views.py

I force pushed to this branch while the PR was closed, so git won't let me reopen #34 . The difference is the addition of a side bar that allows users to plot all the histograms for a single branch, or a summary page with everying in tiled plots. It also adds the run type/start time to the run page.
Accompanies #snoplus/nearline/15
* Serve the .root/.zip files containing histograms/ntuples produced by the nlrat processor and placed in space shared with the nearline machine. Corresponds to views /rat/r104_nl_th1f.root and rat/r104_nl_ntups.root for run 104
*  rathome.html shows the available run numbers, types and start times using functions defined in nlrat.py. Corresponds to view rat
*    ratrun.html and rat.js use JSROOT to display histograms for a run, either by branch or a summary …

Add Rat tab (mark 2)

---

minard/templates/nearline.html

Just noticed that I don't have a case to deal with my own error code.

Update nearline page to reflect signal error code

---

minard/detector_state.py

that keeps other useful information from being returned when the relay states are unknown.
For a good example of where this is useful see run 101655.

Remove a continue in detector state check

---

minard/pingcratesdb.py
minard/templates/layout.html
minard/templates/pingcrates.html
minard/templates/pingcrates_run.html
minard/views.py

This adds a ping crates page that displays information about the CAEN trigger signals during ping crates. The nearline processor that creates the plots is here: https://github.com/snoplus/nearline/pull/95.

Ping crates page

---

bin/mtca_baseline

This is to avoid having to restart the script every time the timing rack is powered off. Havent tested it yet though

Modify baseline monitor script to try more and spam less

---

minard/detector_state.py

Currently we have "crate 19" N100 disconnected. Ping crates has shown that it is mapped to crate 9.

Add spare to MTCA/+ relay check

---

minard/channeldb.py
minard/static/js/discriminator.js
minard/templates/discriminator_info.html
minard/templates/max_thresholds.html
minard/views.py

This makes the discriminator page much more useful by allowing one to compare thresholds between two runs. It also fixes an issue grabbing the correct zdisc information.

updates to discriminator page

---

minard/channeldb.py
minard/templates/channel_status.html

when trying to grab polling info that doesn't exist. Noticed when cmos rate polling was empty for crate 10 slot 10 for run 105820.

update channel status so it doesn't fail

---

minard/channelflagsdb.py
minard/nearline_monitor.py
minard/occupancy.py
minard/pingcratesdb.py
minard/static/css/minard.css
minard/static/js/trigger_occupancy.js
minard/templates/channelflags.html
minard/templates/channelflagsbychannel.html
minard/templates/nearline_monitoring_summary.html
minard/templates/occupancy_by_trigger.html
minard/templates/occupancy_by_trigger_run.html
minard/templates/pingcrates.html
minard/templates/trigger_clock_jump.html
minard/triggerclockjumpsdb.py
minard/views.py

- Ability to select by run for all nearline monitoring pages
- Include new esumh occupancy table that fixes the very slow trigger occupancy pages
- Trigger occupancy by run page now just shows esumh, n100, n20
- Channel flags page now display out-of-sync channels for previous runs
- Add a more in depth description of what the nearline monitoring page is showing for each page

Fixes to nearline monitoring

---

minard/detector_state.py
minard/polling.py

It's spamming too much, and a hard limit doesn't really work because our rates are much lower now with the lower discriminator thresholds. This hasn't really been useful, so I just decided to remove it. The trigger occupancy page should picked up crates with slots tripped off on and run by run basis.

Remove polling limit on detector state check page

---

minard/detector_state.py

We started using channel 7 rather than channel 2 starting on run 107556. 
See this shift report for details: http://snopl.us/shift/view/d4a225af60c6410998f19f7495c4899f.

update tubii channel mapping

---

minard/templates/check_rates_summary.html

based on when the disc thresholds were raised. Crate 8 often fails the
low occupancy check now.

make check rates summary check run dependent

---

minard/nearline_settings.py
minard/templates/nearline_summary.html
minard/views.py

Allow nearline summary page to be sorted by "critical" job types, where "critical" is defined as jobs required for processing a physics run and run selection. Also add muon follower to the list of nearline jobs.

New "critical" job type and add muon follower to nearline table list

---

minard/channelflagsdb.py
minard/nearline_monitor.py
minard/templates/channelflags.html
minard/views.py

Should also fix a bug where if the previous run was resynced and there was no sync 16 in that run (other than the resync) than the next run reported that the channels were out of sync.

Add resync information to channel flags page

---

minard/templates/dropout_detail.html

Zooming in isn't all that useful on this page so I just removed it.

fix bug where dropout detail page had weird zooming.

---

minard/templates/noise.html

Adds two plots generated on nearline to the general noise page, and sorts run details below in descending.

add crate-level plots to noise page; reverse run ordering on noise page

---

minard/detector_state.py

Also I added a warning about channels with thresholds maxed but triggers on, that will be pretty spammy across the entire run range, and would require a change to how the nominal trigger settings are defined, so I can remove that for this pull request. I do think we should not be enabling triggers for channels with maxed thresholds.

Detector state check warn about consectuive channels with vthr maxed at high voltage 

---

minard/nearlinedb.py
minard/templates/check_rates.html
minard/templates/layout.html
minard/templates/nearline.html
minard/templates/nearline_failures.html
minard/views.py

- Move check rates summary page from the layout
- Fix bug where jobs that failed multiple times for the same run were being double counted on the failures page
- Post reprocessing information to nearline page

Nearline failures / reprocessing / check rates summary changes

---

minard/detector_state.py
minard/templates/layout.html
minard/templates/nhit_monitor_nearline.html
minard/templates/nhit_monitor_thresholds_nearline.html
minard/views.py

Use the nearline database for the nhit monitor page. You can go back to using the old page by removing the "nearline" in the url.

Nhit monitor update

---

minard/muonsdb.py

When a run is processed multiple times, display the info for the most recent processing on the muons run page. Check run 104292 for an example.

Order by most recent processing

---

minard/muonsdb.py
minard/nearline_monitor.py
minard/templates/muon_list.html
minard/templates/muons_by_run.html
minard/views.py

muons, atmospherics, and missed muons come within the time
range defined by the stop and start times of the run tables.
This is calculated on the nearline and the time_check table
is filled with that information. This also changes the event
times to be displayed in local time (EST) for direct comparison
to the runs page.
This is in response to several old runs having issues with the
times of the muons being outside the run range, probably due
to some issue with the clock reconstruction. This will allow
run-selection to immediately pick up on such an issue.

Add a check that the event times of the

---

minard/detector_state.py

GT crate mask is used in line 366, which crashes if MTC state is unknown. See run 201233.

initialize gt crate mask in detector state check

---

minard/shifter_information.py

The name "José" breaks the webpage when using str().

fix for non-ascii character issue

---

minard/templates/crate_gain_history.html

There is sometimes data available by adjusting the QHS range. See: https://snopl.us/monitoring/crate_gain_history?ending_run=203329&crate=7&starting_run=203229 for example. 
Note, a fix would be to ignore screamers when calculating the QHS average for each crate, which is what causes the bad measurement.

update message for the crate gain page

---

minard/channelflagsdb.py
minard/nearline_monitor.py
minard/views.py

Fix bugs related to missed burst counting when selecting by run number. See run 117912 for an example of the fix.

channel flags bug fix

---

minard/pmtnoisedb.py
minard/static/js/cratelevelgraphs.js
minard/templates/noise.html
minard/views.py

This PR changes the pmt noise/charge time-series from ugly root plots to the dynamic style used in other monitoring tools, and changes the abscissa from run number to a meaningful date. see below for example.
All of the logic is there, but:
1) We probably want the crate-selection checkboxes to look a bit better than currently
2) Showing more than a few crates at once is a bit intense, resource-wise, for the average laptop
3) The in-plot legend falls off-screen and should be corrected

dynamic noise rate timeseries

---

minard/templates/calibdq_tellie_subrun.html

Adding pulse delay plot produced by telliedq processor. Runs processed before Martti's PR (rat #2475) will not have this image, so text outlining this is displayed for those runs

Show pulse delay distribution plot

---

minard/pmtnoisedb.py
minard/static/js/cratelevelgraphs.js
minard/templates/noise.html
minard/views.py

This PR achieves two improvements:
1) Change the time associated with each run to be more precise.
2) By default, plot only detector-average quantities. Per-crate time-series are available.

Fix noise times

---

minard/static/js/check_rates.js

To reproduce issue: open up the check rates page, change the crate view for the base current to something other than crate 0, then click one of the channels to take you to the history page. It will bring you to the page for crate 0 rather than the correct crate (associated with the base current you clicked).

correct link when clicking the channel on the base current crate

---

minard/detector_state.py

Currently if crate 3/13/18 HV is OFF but the OWL HV is ON, this prints warning messages if triggers are turned on for crate 3/13/18 slot 15.

update owl hv triggers check

---

bin/minard-dispatch

Requires changing the definition of an orphan for the stream page purposes (I think this should be the same as how Xsnoed defines an orphan). Addresses issue #241.

add NONE type triggers to the minard dispatch

---

minard/templates/burst_run_detail_l3.html

Just a small update for the Supernova Burst trigger monitoring page. Specifically, the burst detail page for L3 burst now includes data relating to the supernova alarm: the time of the first high NHit event and the nanoseconds associated with the time.

SN burt trigger: added SN alarm related data

---

minard/presn.py
minard/templates/presn_run_detail.html

1. Default display now sorts by descending run number, rather than by time (in case there's a discrepancy)
2. Details view for a run now displays coincidence times (as rounded by the monitor)

Two small changes to the pre-supernova page:

---

minard/RSTools.py
minard/templates/runselection.html
minard/templates/runselection_run.html
minard/views.py

Fixed the following issues (from run-selection git-issues):
- [x ] Add "search by date" to main page functionality, for run time not run review time?
- [x ] back/next buttons on individual run pages
- [x ] some failed processors show as purgatory, see run 307719 for example
- [x ] run has failed because DQHL failed, but really DQHL purgatoried. see run 307906, the minard page is misreading the .json file  ->  Duplicate issue
- [x ] The value column shouldn't have the threshold label. This is pulled from the json, which should be corrected.
- [x ] Add a button that changes a purgatory run to pass or fail by creating a new version of the .json file. (also allows failing of passed run, or passing of failed run).
- [x ] Add column with timestamp for when run was taken.
- [x ] Currently the …

Run-Selection Page Fixes and Improvements

---

minard/templates/layout.html

Correct a rotten link on minard, which should point to the pmtcal page running on site as opposed to the old site running at Berkeley.

update dropdown link to onsite pmtcal instance

---

README
minard/RSTools.py
minard/templates/runselection.html
minard/templates/runselection_run.html
minard/views.py

A few small changes:
- Modified drop down menu of criteria in run page.
- Fixed small bug with auto-filled criteria in pass/fail form.
- Made run-selection action use new RS_EXPERT password, instead of detectorDB password.
Tested locally, and it works.
NOTE:
Needs a new entry called `RS_EXPERT_PASS='placeholder'` added to the settings.conf file when this is moved to the minard machine, to define the RS_EXPERT password.

Drop-down menu and password change

---

minard/RSTools.py
minard/templates/runselection_plots.html
minard/views.py

The run selction plots page has recently stopped working. This coincides with the recent additions to the bronze and silver lists which suggests that the issue is due to this. Before, the code would download every run table for the user specified criteria and then filter through them using the user specified date range. The reason for downloading all the run tbales is because the date range can't be applied at the db query level. The newly added runs means that more run tables need to be downloaded and I think the page is just crashing at this point. To speed this up and prevent it from crashing, the code now downloads 100 runs at a time until the user specified date range has been satisfied.
A future PR will be to add the ability to use a run range. Run ranges can be applied when …

Fix issue with run selection plots
